-- MySQL Script generated by MySQL Workbench
-- Wed May 31 11:45:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BeerStoreDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BeerStoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BeerStoreDB` DEFAULT CHARACTER SET utf8 ;
USE `BeerStoreDB` ;

-- -----------------------------------------------------
-- Table `BeerStoreDB`.`tblProductCategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeerStoreDB`.`tblProductCategories` ;

CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`tblProductCategories` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NOT NULL,
  `prod_type` VARCHAR(45) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeerStoreDB`.`tblProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeerStoreDB`.`tblProducts` ;

CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`tblProducts` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_name` VARCHAR(45) NULL,
  `company_name` VARCHAR(45) NULL,
  `prod_description` MEDIUMTEXT NULL,
  `prod_picture` VARCHAR(255) NULL,
  `prod_package` VARCHAR(45) NULL,
  `prod_price` DECIMAL(9,2) NULL,
  `cat_id` INT NOT NULL,
  PRIMARY KEY (`prod_id`, `cat_id`),
  INDEX `fk_products_categories1_idx` (`cat_id` ASC),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `BeerStoreDB`.`tblProductCategories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeerStoreDB`.`tblUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeerStoreDB`.`tblUsers` ;

CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`tblUsers` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeerStoreDB`.`tblOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeerStoreDB`.`tblOrders` ;

CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`tblOrders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `order_date` DATETIME NULL,
  `payed` TINYINT(1) NOT NULL DEFAULT 0,
  `order_total` DECIMAL NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeerStoreDB`.`tblOrders_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeerStoreDB`.`tblOrders_Products` ;

CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`tblOrders_Products` (
  `order_id` INT NOT NULL,
  `product_id` INT NULL,
  `quantity` INT NULL,
  `total` DECIMAL NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `BeerStoreDB`.`tblOrders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
