-- MySQL Script generated by MySQL Workbench
-- Sun May  7 20:38:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BeerStoreDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BeerStoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BeerStoreDB` DEFAULT CHARACTER SET utf8 ;
USE `BeerStoreDB` ;

-- -----------------------------------------------------
-- Table `BeerStoreDB`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`categories` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(200) NOT NULL,
  `cat_description` VARCHAR(250) NULL,
  `parent_cat` INT NULL,
  `categories_cat_id` INT NOT NULL,
  PRIMARY KEY (`cat_id`, `categories_cat_id`),
  UNIQUE INDEX `cat_id_UNIQUE` (`cat_id` ASC),
  INDEX `fk_categories_categories_idx` (`categories_cat_id` ASC),
  CONSTRAINT `fk_categories_categories`
    FOREIGN KEY (`categories_cat_id`)
    REFERENCES `BeerStoreDB`.`categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeerStoreDB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeerStoreDB`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NOT NULL,
  `product_price` DECIMAL NOT NULL,
  `product_category` INT NULL,
  `product_description` VARCHAR(250) NULL,
  `cat_id` INT NULL,
  `product_image` VARCHAR(250) NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  INDEX `fk_products_categories1_idx` (`cat_id` ASC),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `BeerStoreDB`.`categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
